lbin = {
    "lx": "1",
    "ly": "1",
    "lz": "252",
    "geometryLabel": "1",
    "SolidSheetsEachSideOfSlit": "3",
    "capacitor": "0",
    "slit_sol": "0",
    "tot_sol_charge": "0.0",
    "charge_distrib": "int",
    "Constant_Potential": "1",
    "FixedPotentialUP": "1e-3",
    "FixedPotentialDOWN": "0",
    "LB1": "1",
    "UB1": "2",
    "LB2": "1",
    "UB2": "2",
    "bjl": "{bjl}",
    "lambda_D": "{lambda_D}",
    "D_plus": "0.05",
    "D_minus": "0.05",
    "D_iter": "1",
    "f_ext": "0.0 0.0 0.0",
    "elec_slope": "0.0 0.0 0.0",
    "lncb_slope": "0.0 0.0 0.0",
    "target_error_mass_flux": "1.0e-7",
    "target_error_charge": "1.0e-7",
    "target_error_sor": "1.0e-8",
    "timestepmax_for_PoissonNernstPlanck": "100000",
    "RestartPNP": "T",
    "write_total_mass_flux": "F",
    "print_every": "1000",
}

phin = {
    "dx": "3e-9",
    "Lx": "3e-9",
    "Ly": "3e-9",
    "Lz": "100e-9",
    "solid nodes": "3",
    "Potential up": "1.1e-3",
    "Potential down": "0.1e-3",
    "epsilon_r": "78.4",
    "Temp": "298",
    "C_inf": "0.005",
}
